name: Project Build
on: [push]

jobs:
  release:
    name: Build MD5 Endpoint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Enpoint
      run: |
        file=usr/share/bash-completion/completions/lolcat
        [[ -f "$file" ]] || exit 127
        lolcat_complete_md5_text='{\n\t"schemaVersion": 1,\n\t"color": "ffff99",\n\t"label": "lolcat Bash Completion MD5",\n\t"message": "PLACEHOLDER",\n\t"labelColor": "1d1d1d",\n\t"style": "for-the-badge",\n\t"namedLogo": "bash"\n}'
        if ! [[ -d "docs/json" ]]; then
          mkdir -p docs/json || exit 126
        fi
        if ! [[ -f "docs/json/lolcat_complete_md5.json" ]]; then
          touch "docs/json/lolcat_complete_md5.json" || exit 125
        fi
        echo -e "$lolcat_complete_md5_text" > "docs/json/lolcat_complete_md5.json"
        sed -i "s/\"message\": \".*\"/\"message\": \"$(md5sum $file | cut -d' ' -f 1)\"/g" "docs/json/lolcat_complete_md5.json"
        git add docs/json/*
        git config --global user.name 'Lateralus138'
        git config --global user.email 'Lateralus138@users.noreply.github.com'
        git commit --allow-empty -am "Pushed $(printf '%s ' docs/json/*) to master. - $(date -u)"
        git push --force origin master
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        tag: 1.0.0
        name: Stable Release
        bodyFile: ./docs/md/release.md
        prerelease: False
        artifacts: ./usr/share/bash-completion/completions/lolcat
        token: ${{ secrets.GITHUB_TOKEN }}
